### ISSUE TITLE
Unable to install dependencies and run the application

### ISSUE THREAD

**Issue by anirudh-0** [PSMRI/Admin-UI-ARCHIVED#31]
# Application Setup Directions needed
I have tried to install the dependencies with node v6, node v16, node v18.
I seem to be encountering a dependency issue w.r.t node-sass.
Is there something I have to install or change my node engine somehow ?

**Comment by drtechie** [comment]
@anirudh-0 
Try with v8.9.0
Check the readme here.
https://github.com/PSMRI/HWC-UI

**Comment by drtechie** [comment]
Keeping this issue open as the setup instructions are not complete.

**Comment by drtechie** [comment]
`v8.9.0` doesn't work well with `node-sass`.

`node-sass` installation results in following error.

```
> node-sass@9.0.0 install /Users/drtechie/Dev/PSMRI/Admin-UI/node_modules/node-sass
> node scripts/install.js

/Users/drtechie/Dev/PSMRI/Admin-UI/node_modules/@npmcli/fs/lib/fs.js:6
const fsSync = Object.fromEntries(Object.entries(fs).filter(([k, v]) =>
                      ^

TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (/Users/drtechie/Dev/PSMRI/Admin-UI/node_modules/@npmcli/fs/lib/fs.js:6:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/drtechie/Dev/PSMRI/Admin-UI/node_modules/@npmcli/fs/lib/index.js:2:6)
    at Module._compile (module.js:635:30)

```

`Object.fromEntries` is available only in later versions of Node.

Node 14 on the other hand gives compilation errors.


```
* NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
 11% building modules 16/27 modules 11 active ...ode_modules/style-loader/addStyles.jswebpack: wait until bundle finished: /
Hash: 27237de6099d8b3c46bd                                                                
Time: 14929ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 3.58 MB {4} [initial] [rendered]
chunk    {1} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 192 kB {5} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 407 kB {5} [initial] [rendered]
chunk    {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 154 kB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 7.06 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (148,34): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (155,15): ',' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (155,30): ',' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (155,47): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (196,23): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (245,27): ',' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (245,34): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (291,22): ',' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (291,29): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (303,13): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (307,13): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (312,52): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (322,22): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (326,30): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (331,17): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (337,1): '}' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (148,3): Unreachable code detected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (75,14): Property 'loginUser' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (82,10): Property 'getCommitDetails' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (91,12): Property 'successCallback' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (128,20): Property 'generateKeyWithPBKDF2' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (148,3): Cannot find name 'encrypt'. Did you mean 'encrypted'?

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (155,3): Cannot find name 'login'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (155,9): Cannot find name 'userId'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (155,17): 'any' only refers to a type, but is being used as a value here.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (155,22): Cannot find name 'password'. Did you mean the instance member 'this.password'?

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (155,32): 'any' only refers to a type, but is being used as a value here.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (155,37): Cannot find name 'doLogout'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (156,33): Property 'encrypt' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (156,54): Cannot find name 'password'. Did you mean the instance member 'this.password'?

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (157,9): Cannot find name 'userId'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (160,48): Cannot find name 'userId'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (160,78): Cannot find name 'doLogout'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (183,42): Cannot find name 'userId'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (183,72): Cannot find name 'doLogout'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (186,16): Property 'successCallback' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (189,16): Property 'errorCallback' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (196,3): Cannot find name 'loginUser'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (196,13): Cannot find name 'doLogOut'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (203,87): Cannot find name 'doLogOut'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (227,79): Cannot find name 'doLogOut'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (230,18): Property 'successCallback' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (233,18): Property 'errorCallback' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (245,3): Cannot find name 'successCallback'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (245,19): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (245,29): 'any' only refers to a type, but is being used as a value here.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (246,17): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (247,40): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (248,46): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (249,35): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (251,37): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (252,26): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (254,9): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (254,46): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (255,57): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (256,46): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (257,32): Property 'getServiceProviderMapIDSuccessHandeler' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (260,27): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (263,13): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (279,9): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (279,46): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (281,43): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (285,25): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (286,11): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (287,60): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (291,3): Cannot find name 'errorCallback'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (291,17): Cannot find name 'error'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (291,24): 'any' only refers to a type, but is being used as a value here.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (292,9): Cannot find name 'error'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (293,26): Cannot find name 'error'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (298,17): Cannot find name 'error'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (303,3): Cannot find name 'showPWD'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (307,3): Cannot find name 'hidePWD'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (312,3): Cannot find name 'getServiceProviderMapIDSuccessHandeler'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (312,42): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (313,44): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (314,9): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (315,52): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (316,32): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (322,3): Cannot find name 'getCommitDetails'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (324,88): Property 'successhandeler1' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (324,123): Property 'successhandeler1' does not exist on type 'loginContentClass'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (326,3): Cannot find name 'successhandeler1'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (326,20): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (327,26): Cannot find name 'response'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/login/login.component.ts (331,3): Cannot find name 'ngOnDestroy'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (72,3): Unexpected token. A constructor, method, accessor, or property was expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (116,37): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (189,37): ';' expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (209,1): Declaration or statement expected.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (68,10): Property 'getAllUserName' does not exist on type 'ResetUserPasswordComponent'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (74,10): Property 'keySize' does not exist on type 'PasswordManager'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (75,10): Property 'iterationCount' does not exist on type 'PasswordManager'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (76,10): Property 'ivSize' does not exist on type 'PasswordManager'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (81,10): Property 'tableMode' does not exist on type 'PasswordManager'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (82,10): Property 'resetUserPasswordService' does not exist on type 'PasswordManager'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (84,14): Property 'userDetails' does not exist on type 'PasswordManager'. Did you mean 'getUserDetail'?

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (93,21): Property 'keySize' does not exist on type 'PasswordManager'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (94,24): Property 'iterationCount' does not exist on type 'PasswordManager'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (107,49): Property 'ivSize' does not exist on type 'PasswordManager'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (108,51): Property 'keySize' does not exist on type 'PasswordManager'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (116,3): Cannot find name 'getAllUserName'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (116,18): Cannot find name 'serviceProviderID'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (117,47): Cannot find name 'serviceProviderID'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (189,3): Cannot find name 'resetPassword'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (189,17): Cannot find name 'userName'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (189,27): Cannot find name 'password'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (191,19): Cannot find name 'userName'.

ERROR in /Users/drtechie/Dev/PSMRI/Admin-UI/src/app/reset-user-password/reset-user-password.component.ts (192,45): Cannot find name 'password'.

ERROR in /users/drtechie/dev/psmri/admin-ui/node_modules/@types/node/index.d.ts (20,1): Invalid 'reference' directive syntax.
webpack: Failed to compile.

```
